### ISSUE TITLE
filter.guassianBlur is not a function

### ISSUE THREAD

**Issue by 1forh** [bradmartin/nativescript-image-filters#1]
I am passing an image from one view to another using `navigationContext`. I want to then apply a Gaussian blur to the image once the user navigates to the view.

Here is my code:

```JavsaScript
var Observable = require('data/observable').Observable;
var ImageFilters = require('nativescript-image-filters').ImageFilters;
var page;

var filter = new ImageFilters();

exports.navigatedTo = function(args) {
	page = args.object;
	page.bindingContext = page.navigationContext;
	blur(page.bindingContext.image);
};

function blur(pic) {
	filter.gaussianBlur(pic)
		.then(function(result) {
			pic = result;
		}).catch(function(err) {
			console.log('applyFilter ERROR: ' + err);
		});
}
```

However, I am getting this error: 

```
JS ERROR TypeError: filter.gaussianBlur is not a function. (In 'filter.gaussianBlur(pic)', 'filter.gaussianBlur' is undefined)
```

I have even tried to copy/paste your sample code to see if that would work and I get the same error. I have also tried using different effects but I get the same error message for each effect. Am I missing a step?

**Comment by bradmartin** [comment]
Hi @1forh - if that's happening on all of the methods then you have something else wrong, I have a few suggestions :)

1. Uninstall the current build of your app from device/emulator.
2. Run `tns platform remove android` then `tns platform add android`
3. `tns build android`
4. Run the new build on your device/emulator.

I'm assuming you had an .apk, added the plugin and never did the above. Reason you need to us because the 3rd party native library needs to be packaged into your app during the android build. So it was never in the app you're running, make sense? Plugins not using native libraries don't typically require this process.

**Comment by 1forh** [comment]
So it seems like I only get this error in iOS. Does this only support Android right now?

**Comment by bradmartin** [comment]
Yea, I normally note that on the README. Whoops :( sorry

**Comment by 1forh** [comment]
No problem! You can close this issue then. Thanks for the help!
