### ISSUE TITLE
greyScale() doesn't seem to be implemented 

### ISSUE THREAD

**Issue by RoyalSWiSH** [bradmartin/nativescript-image-filters#13]
Hi,

I am using Nativescript Vue with Typescript to do some image enhancement. The method greyScale(img: Image) can be found in `index.d.ts`, but is not implemented in `imagefilters.android.js` or `imagefilters.ios.js`. 

This works fine:
```
let pic =  <Image> topmost().currentPage.getViewById('myPicture');
let filters = new ImageFilters();
filters.invert(pic)
```

When I change the last line to:

`filters.greyScale(pic)`

I get this error:

`System.err: TypeError: filters.greyScale is not a function`

I hope I did not miss something, maybe I will attempt to work on it, but for now I am just leaving an issue here.

Greets,
Sebastian Roy

**Comment by bradmartin** [comment]
Thanks for issue. The typings info is incorrect. I called that filter `blackAndWhite` so try using that method instead of `greyScale()`

In the demo it's used here https://github.com/bradmartin/nativescript-image-filters/blob/master/demo/app/main-view-model.ts#L45
and I forgot to update the README gif that showed a different term on the Button :)

I'll update the API thanks.
